parser: babel-eslint
extends: airbnb
rules:
  no-console:
    off
  camelcase:
    off
  import/extensions:
    off
  react/no-array-index-key:
    off
  react/prop-types:
    off
globals:
  document: false
  window: false