parser: babel-eslint
extends: airbnb
rules:
  no-console:
    off
  camelcase:
    off
  import/extensions:
    off
  react/no-array-index-key:
    off
  react/prop-types:
    off
  jsx-a11y/click-events-have-key-events:
    off
  jsx-a11y/no-static-element-interactions:
    off
globals:
  document: false
  window: false